/**
 * ApiTap — HAR builder
 * Minimal HAR 1.2 export from correlator calls. Reuses captured fields; no chrome APIs.
 * Dual-exported for service worker and Node tests.
 */
(function (root, factory) {
  const mod = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = mod;
  root.HarBuilder = mod;
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  function headerArrayToHar(list) {
    return (list || []).map(function (h) { return { name: h.name || h.key || '', value: h.value != null ? String(h.value) : '' }; });
  }
  function buildHar(correlator) {
    var calls = (correlator.calls || []).filter(function (c) { return c.checked !== false; });
    var entries = calls.map(function (call) {
      var url = call.url || '';
      var u, query = [];
      try {
        u = new URL(url);
        u.searchParams.forEach(function (v, k) { query.push({ name: k, value: v }); });
      } catch (e) { }
      var reqHeaders = headerArrayToHar(call.requestHeaders);
      var resHeaders = headerArrayToHar(call.responseHeaders);
      var started = new Date(call.ts || Date.now()).toISOString();
      var postData = null;
      if (call.requestBody) {
        var mime = 'text/plain';
        for (var i = 0; i < reqHeaders.length; i++) if (String(reqHeaders[i].name).toLowerCase() === 'content-type') { mime = String(reqHeaders[i].value).split(';')[0].trim() || mime; break; }
        postData = { mimeType: mime, text: call.requestBody };
      }
      var content = { size: call.responseBody ? call.responseBody.length : 0, mimeType: 'text/plain' };
      for (var j = 0; j < resHeaders.length; j++) if (String(resHeaders[j].name).toLowerCase() === 'content-type') { content.mimeType = String(resHeaders[j].value).split(';')[0].trim() || content.mimeType; break; }
      if (call.responseBody) content.text = call.responseBody;
      return {
        startedDateTime: started,
        time: 0,
        request: { method: call.method || 'GET', url: url, httpVersion: 'HTTP/1.1', headers: reqHeaders, queryString: query, cookies: [], headersSize: -1, bodySize: -1, postData: postData },
        response: { status: call.status != null ? call.status : 0, statusText: '', httpVersion: 'HTTP/1.1', headers: resHeaders, cookies: [], content: content, redirectURL: '', headersSize: -1, bodySize: -1 },
        cache: {},
        timings: { send: 0, wait: 0, receive: 0 }
      };
    });
    return { log: { version: '1.2', creator: { name: 'ApiTap', version: '1.1.0' }, pages: [], entries: entries } };
  }
  function buildOpenApi(correlator) {
    var calls = (correlator.calls || []).filter(function (c) { return c.checked !== false; });
    var groups = new Map();
    for (var i = 0; i < calls.length; i++) {
      var k = correlator.groupKey(calls[i]);
      if (!groups.has(k)) groups.set(k, []);
      groups.get(k).push(calls[i]);
    }
    var paths = {};
    var baseUrl = '';
    try {
      var tally={}; for(var _t=0;_t<calls.length;_t++){ try{ var o=new URL(calls[_t].url).origin; tally[o]=(tally[o]||0)+1; }catch(e){} }
      var best=null, bestN=0; for(var k in tally) if(tally[k]>bestN){ best=k; bestN=tally[k]; }
      if(best) baseUrl=best; else if(calls[0]) baseUrl=new URL(calls[0].url).origin;
    } catch (e) {}
    groups.forEach(function (list, key) {
      var parts = key.split('|');
      var method = (parts[0] || 'GET').toLowerCase();
      var path = parts[2] || '/';
      if (!paths[path]) paths[path] = {};
      var sample = list[0];
      var respExample = null;
      try { if (sample.responseBody) respExample = JSON.parse(sample.responseBody); } catch (e) { respExample = sample.responseBody; }
      paths[path][method] = {
        summary: key,
        description: 'Stub generated by ApiTap — not a spec. ' + list.length + ' captured call(s).',
        responses: { '200': { description: 'Example', content: respExample ? { 'application/json': { example: respExample } } : undefined } }
      };
    });
    return { openapi: '3.0.0', info: { title: 'ApiTap — Recorded stub', version: '1.0.0', description: 'Auto-generated stub from recorded flow. Review before use.' }, servers: baseUrl ? [{ url: baseUrl }] : [], paths: paths };
  }
  return { buildHar: buildHar, buildOpenApi: buildOpenApi };
});
